version: '3'

services:
    gateway:
        image: kong:0.12-alpine
        environment:
            - "KONG_DATABASE=postgres"
            - "KONG_PG_HOST=db"
            - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
            - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
            - "KONG_PROXY_ERROR_LOG=/dev/stderr"
            - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
            - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
            - "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444"
        ports:
            - "8000:8000"
            - "8001:8001"
        # networks:
        #     - "example"
    db:
        image: postgres:10-alpine
        container_name: "kong-database"
        environment:
            - "POSTGRES_USER=kong"
            - "POSTGRES_DB=kong"
        # networks:
        #     - "example"

networks:
    default:
        external:
            name: kongexample
